### ISSUE TITLE
Can not create instance of domains which are value decorators  

### ISSUE THREAD

**Issue by o-rumiantsev** [metarhia/metaschema#118]
Function `createInstance` in `lib/schema.js` can not create instances of domains which are value decorators, because we can not specify `type` field for them. 

https://github.com/metarhia/metaschema/blob/aac7ad16ce34cc6a066f850f5a99ddcb9bcf232f/lib/schema.js#L137-L141

Here an identifier `type` is an own JS type of `value`, but `expected` is `name`(name of the category, we creating instance of), because value decorators `Enum` and `Flags` can not have property `type`. So `type === expected` is `false` and it returns `null`

**Comment by tshemsedinov** [comment]
Yes, please fix this adding additional check if `domain.constructor.name` will be `Enum` or `Flags` we need to validate `value` to be one of allowed in `Enum` and `Flags` respectively. @o-rumiantsev
