### ISSUE TITLE
Formatting for example/result

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metaschema#14]
Combine into code block
```
Example: method(arguments);
Result: { name: value }
```

**Comment by SemenchenkoVitaliy** [comment]
Documentation generator was removed in https://github.com/metarhia/metaschema/pull/182 from [@metarhia/metaschema](https://github.com/metarhia/metaschema) and moved to [@metarhia/metadoc](https://github.com/metarhia/metadoc). As for the issue, [@metarhia/metadoc](https://github.com/metarhia/metadoc) supports `Example` and `Result` comments starting from [v0.1.0](https://github.com/metarhia/metadoc/releases/tag/v0.1.0).
