### ISSUE TITLE
Validate `Id` field (csv import)

### ISSUE THREAD

**Issue by o-rumiantsev** [metarhia/metaschema#142]
We need to validate the `Id` field, which implicitly exists in any object.

**Comment by tshemsedinov** [comment]
We add `Id` field automatically only in database schemas and we never define it explicitly
/cc @nechaido @belochub

**Comment by nechaido** [comment]
We do not define it, yet we may pass an object, that contains `Id` field, in that case metaschema validate will produce an error.

**Comment by tshemsedinov** [comment]
Not relevant for 1.x
