### ISSUE TITLE
Update metarhia-common

### ISSUE THREAD

**Issue by aqrln** [metarhia/metaschema#143]
`metaschema` depends on an old version of `metarhia-common` which is broken in browser environment.

Ref: https://github.com/metarhia/common/issues/211

/cc @tshemsedinov @nechaido

**Comment by SemenchenkoVitaliy** [comment]
Can confirm that this is also because of an old `metasync` which should be updated as well.

**Comment by SemenchenkoVitaliy** [comment]
BTW, `metaschema` can't work in the browser because it uses `fs` to load schemas and verify links.

**Comment by belochub** [comment]
Closing the issue since `metarhia-common` was updated in https://github.com/metarhia/metaschema/commit/e86880d31592a388054afb2d7ba9f5f975c0b24b.
