### ISSUE TITLE
ApplicationMenu description

### ISSUE THREAD

**Issue by nechaido** [metarhia/metaschema#171]
We need a way to define a Menu in an application schema. The proposed structure is:
```js
MenuItem = {
  type: Enum('caterory', 'projection', 'group', 'separator'),
  name: { domain: 'Nomen' },
  icon: { domain: 'Nomen', comment: 'resource key for menu entry icon' },
  items: Array('MenuItem'),
};

ApplicationMenu = Array('MenuItem');
```

**Comment by lundibundi** [comment]
I'd propose:
```js
MenuItem = {
  type: Enum('category', 'projection', 'group', 'separator'),
  name: { domain: 'text' },
  icon: { domain: 'text', comment: 'resource key for menu entry icon' },
  items: List('MenuItem'),
};

ApplicationMenu = List('MenuItem');
```

Fixed a few typos.
I think 'Nomen' is way too limited, so switched to text.
I don't think we have 'Array' decorator, 'List'?

**Comment by igorgo** [comment]
The `name`  prop is a name of category or projection, isn`t? Аnd where is the most important thing. Where is the **internationalized** text to display?

**Comment by nechaido** [comment]
@igorgo 
> The name prop is a name of category or projection, isn`t? 

Yes, it is.

As per internationalized string, I believe that resources should be stored somewhere else, not in the schema.
