### ISSUE TITLE
Inter-operation and maintainability improvements

### ISSUE THREAD

**Issue by lundibundi** [metarhia/metaschema#181]
Interop:
- [ ] serialization of schemas from JS object (Metaschema Object)
- [x] incremental schemas addition to Metaschema
- [ ] a way to filter out properties and connections (based on rules/permissions/needs)

Maintainability:
- [x] a way to split Schema into multiple files/directories (@nechaido)

Utils:
- [ ] a way to implement, place and use internal JS modules/libraries in schemas

/cc @tshemsedinov, @nechaido, @belochub

**Comment by tshemsedinov** [comment]
Not relevant for 1.x
