### ISSUE TITLE
loadAndCreate duplicates default domains schema

### ISSUE THREAD

**Issue by o-rumiantsev** [metarhia/metaschema#204]
When `loadAndCreate` called with `schemas/metaschema` as `dir` argument, it produces duplication errors, because it loads all schemas from `schemas/metaschema` directory, and then calls `loadModuleSchema` with `domainsPath` as `filepath` argument. So it loads default domains two times.

**Comment by nechaido** [comment]
This is not a bug, this behavior is intentional so that no one overrides default domains by mistake.
