### ISSUE TITLE
Syntax extension proposal

### ISSUE THREAD

**Issue by nechaido** [metarhia/metaschema#214]
Currently, there is no way to define that category is made of any number of properties, which are an instance of a domain or a category, I propose the following syntax:
`category.schema`
```js
{
  [Symbol.for('other')]: ['DomainInstance', 'CategoryInstance'],
}
```

`[Symbol.for('other')]` would be used for validating any property present in an object but not it's definition.
`['DomainInstance', 'CategoryInstance']` would mean that a property must be a valid instance of `DomainInstance` or `CategoryInstance` categories.

Any proposal to improve syntax is welcome.

/cc @belochub @lundibundi @tshemsedinov @aqrln

**Comment by tshemsedinov** [comment]
That's fine. If we need to deny undefined fields: `[Symbol.for('other')]: []`

**Comment by nechaido** [comment]
@lundibundi @belochub @aqrln ping.
