### ISSUE TITLE
Support property documentation

### ISSUE THREAD

**Issue by nechaido** [metarhia/metaschema#23]
We need possibility to document properties.

**Comment by tshemsedinov** [comment]
Property can be added as mixin, Object.assign, Object.defineProperty, etc. We parse function signature in runtime so we can catch all functions added in any way. I do not know how can we do so with properties. We may document it manually or add declaration into constructor function of class/prototype.

**Comment by SemenchenkoVitaliy** [comment]
Documentation generator was removed in https://github.com/metarhia/metaschema/pull/182 from [@metarhia/metaschema](https://github.com/metarhia/metaschema) and moved to [@metarhia/metadoc](https://github.com/metarhia/metadoc). As for the issue, [@metarhia/metadoc](https://github.com/metarhia/metadoc) supports properties starting from [v0.2.1](https://github.com/metarhia/metadoc/releases/tag/v0.2.1).
