### ISSUE TITLE
Library schema type proposal

### ISSUE THREAD

**Issue by nechaido** [metarhia/metaschema#233]
I propose to add a new schema type: `library`,
Example.lib:
```js
const a = 2;

const f = (obj) => obj.a === a;

Export({
  fn: f,
  obj: { a },
});
```
`Export` must be the last expression in a file.
Exported data would be accessible by `lib['library name']`,
Example.category:
```js
{
  a: { ... },
  Check: Validate(obj => lib.Person.fn(obj)),
}
```
Should we specify libraries to be injected explicitly(`[Symbol.for('dependsOn)]: ['Example']`), or should we only inject libraries located in the same modules or maybe all of them?

WDYT @tshemsedinov, @belochub, @lundibundi

**Comment by lundibundi** [comment]
LGTM. I assume the filename would be used as a library name? Perhaps we should allow 
passing `Export({...}, 'name1.name2')` to allow override and nested exports (by splitting via '.')?

I think 'dependsOn' looks good (especially if we allow nested paths in dependencies). Though I won't be opposed to global lib considering we already have other dependencies that way.

**Comment by nechaido** [comment]
ping @belochub @tshemsedinov.

**Comment by nechaido** [comment]
ping @tshemsedinov.

**Comment by tshemsedinov** [comment]
Not relevant for 1.x
