### ISSUE TITLE
Typed tuple

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metaschema#281]
Cases:

Tuple of 3 numbers
Example: `[1, 2, 3]`
Schema: `{ type: 'tuple', value: 'number', length: 3 }`

Tuple of two elements (number and string) field
Example: `['abc', 123]`
Schema: `['string', 'number', '?string']`

Specs: https://github.com/metarhia/Contracts/blob/master/doc/Metaschema.md#collections

**Comment by dmitryt** [comment]
From specs:
>Tuple of 3 numbers: field: `{ type: 'tuple', value: 'number', length: 3 }`
>Tuple of two elements (number and string) `field: ['string', 'number']`

@tshemsedinov, is it longform and shorthand for this type of field or maybe I've missed something?

**Comment by georgolden** [comment]
Did as an example on new version. Done similar as C# Tuple with named fields as well. https://github.com/metarhia/metaschema/pull/402
