### ISSUE TITLE
Validation plugin for IDE

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metaschema#32]
We need plugin for IDE to validate declarative structure (JSON, JSON5, JSTP) or JavaScript and have autocomplete for fields and values defined in schemas. For the first time it will be ok to have such plugin just for single IDE.

**Comment by tshemsedinov** [comment]
@lundibundi now we have schemas to define schemas of schemas:
- [for Domain](https://github.com/metarhia/metaschema/blob/master/taxonomy/Domain.schema)
- [for Category field](https://github.com/metarhia/metaschema/blob/master/taxonomy/CategoryField.schema)
- [for Database category field](https://github.com/metarhia/metaschema/blob/master/taxonomy/DatabaseField.schema)

**Comment by tshemsedinov** [comment]
@lundibundi now we have `{ valid: Boolean, errors: Array } = metaschema.validate(categoryName, instance)` to validate schemas, see examples here: https://github.com/metarhia/metaschema/blob/master/test/validate.js

**Comment by lundibundi** [comment]
Results of the discussion in person:

* `CategoryField.schema` defines each field in any of the `.schema` files (besides Domains.schema, CategoryField.schema, DatabaseField.schema, domains.schema) in [`metaschema/taxonomy`](https://github.com/metarhia/metaschema/tree/master/taxonomy) - basically any Category
* `DatabaseField.schema` defines each field in files from https://github.com/metarhia/globalstorage/tree/master/schemas
* 'cartography and geometry'.. are just for syntax grouping, they don't have any 'namespace'-like meaning and all Categories are in the same namespace (you can use Categories from general in geometry etc.)

* Decorators will be defined in separate file later (by @tshemsedinov)

/cc @tshemsedinov
