### ISSUE TITLE
Disallow top level `type` property

### ISSUE THREAD

**Issue by nechaido** [metarhia/metaschema#324]
**Is your feature request related to a problem? Please describe.**
I frequently forget that I can't have properties named `type` on a schema.

**Describe the solution you'd like**
An error message if we encounter top level property named `type` on a schema.

**Describe alternatives you've considered**
A warning message.

**Comment by tshemsedinov** [comment]
We need it for scalar values:
```js
const def1 = { type: 'string' };
const schema1 = Schema.from(def1); 
if (schema1.check('value').valid) ...
```

**Comment by nechaido** [comment]
Yeah, I know. But we can check this in `Model` constructor or loader.
I highly doubt that one is supposed to have a dedicated file for a primitive type. I'd say you are suppised to list all your domain types in `.types.js`.

That way we can have fully functioning schemas and a warning.
