### ISSUE TITLE
Correctly save relations

### ISSUE THREAD

**Issue by nechaido** [metarhia/metaschema#327]
At the moment the only way to check whether an entity has many-to-many relations is to check the `indexes` property.

It would be good to have a dedicated `relations` property.
Alternatively `references` property could be changed to include info about the reference.

**Additional context**
https://github.com/metarhia/metagram/pull/2#issuecomment-842510559

**Comment by tshemsedinov** [comment]
Example: 
````
relations: Set(2) {
  { to: 'Company', type: 'many-to-one' },
  { to: 'Address', type: 'one-to-many' }
},
````
