### ISSUE TITLE
Schema checking failed

### ISSUE THREAD

**Issue by muturgan** [metarhia/metaschema#331]
Hello dear team :)
Thank you for amazing products!

**My code snippet**
``` js
const { Schema } = require('metaschema');
const definition = {
  field1: 'string',
  field2: {
    subfield1: 'number',
  },
};
const obj = {...};
const schema = new Schema('StructName', definition);
const result = schema.check(obj);
console.log(result);
```

**Describe the bug**
If I define my obj like this:
``` js
const obj = {
  field1: 'value',
  field2: {},
};
```
then my console output will be:
``` js
{ valid: false, errors: [ 'Field "subfield1" is required' ] }
```
that is correct.

But if I try to validate this (and that is possible, may be it is a third party api response):
``` js
const obj = {
  field1: 'value',
};
```
then script will crash and the console output will be:
```
***PATH***/node_modules/metaschema/lib/schema.js:193
    const keys = Object.keys(target);
                        ^
TypeError: Cannot convert undefined or null to object
```

**Expected behavior**
the script should exec correctly and the output like
``` js
{ valid: false, errors: [ 'Field "field2" is required' ] }
```

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Node.js version 14.17.4

**Comment by tshemsedinov** [comment]
Thanks for reporting, will fix asap

**Comment by whiteand** [comment]
@tshemsedinov Seems that it should be closed, because @RoTerentev  fixed it
