### ISSUE TITLE
How to describe an array of specified objects? 

### ISSUE THREAD

**Issue by muturgan** [metarhia/metaschema#364]
Well, after a private call, converting [this](https://github.com/metarhia/metaschema/discussions/363) question to an issue.  
  
I have tried to validate this data structure as a method's return value
``` js
{
  result: "success",
  data: [{
    countryId: "1",
    name: "Soviet Union"
  }]
}
```
via metaschema.
My method's schema is:
``` js
({
  access: 'public',

  returns: {
    result: 'string',
    data: {
      type: 'array',
      value: {
        countryId: 'string',
        name: 'string',
      },
    },
  },

  method: .....
});
```
But a return value from the first code snippet leads to an error:
**Invalid result type: Field "data" expected to be array of [object Object].**  

Looks like this nested validation feature does not implemented yet.

**Comment by tshemsedinov** [comment]
Done: https://github.com/metarhia/metaschema/issues/378
