### ISSUE TITLE
Generating a cross table with one field instead of two

### ISSUE THREAD

**Issue by imnetcat** [metarhia/metaschema#377]
**To Reproduce**

For example I have such a scheme:

_Content.js:_

```
({
  Registry: {},
});
```

I add a `reminders` field with the many relation with current field

_Content.js:_
```
({
  Registry: {},

  reminders: { many: 'Content' },
});
```

Then I run `metasql c`  for generation database.sql

The new cross-table looks like this: 

```
CREATE TABLE "ContentContent" (
  "contentId" bigint NOT NULL
);
```

**Actual behavior**
Due to the fact that the names of the tables are the same, a cross table with one field is obtained

**Expected behavior**
Despite the same schema names, a table with two fields should be generated, for example:

```
CREATE TABLE "ContentContent" (
  "contentId1" bigint NOT NULL,
  "contentId2" bigint NOT NULL
);
```

**Versions**

- metaschema: 1.3.4
- OS: 5.10.68-1-MANJARO x64
- Node.js version 14.17.3

**Additional context**
Not so critical bug

**Comment by georgolden** [comment]
There is no support of recursive relations now. It must be feature request, I think.

**Comment by georgolden** [comment]
@tshemsedinov Can we close? Recursive dependencies are forbidden

**Comment by georgolden** [comment]
Recursive dependency works as reference now. See https://github.com/metarhia/metaschema/blob/6e07922de1afb5a28429895e05f9cc0359895a9c/test/model.js#L104-#L137
