### ISSUE TITLE
Incorrect Schema kind definition

### ISSUE THREAD

**Issue by lundibundi** [metarhia/metaschema#409]
**Describe the bug**
Our current implementation depends on object key ordering to get Schema kind.
https://github.com/metarhia/metaschema/blob/b6615f09f170000238cd62d1aa60beae8cb7ed59/lib/preprocessor.js#L39-L42
Specifically we get "first" by order key from object and assume "insertion" order, but this not correct because there is no such order in the ECMAScript spec.
The Object.keys uses `10.1.11.1 OrdinaryOwnPropertyKeys` https://262.ecma-international.org/12.0/#sec-ordinaryownpropertykeys
Which has specific key order not dependent on "insertion" order.

**To Reproduce**
```js
Object.keys({ Dynamic: {}, field1: 'string', 123: 'number', field2: 'string' })
=>
[ '123', 'Dynamic', 'field1', 'field2' ]
```

Test case (this also fails with other error due to another pre-processing bug)
```js
metatests.testSync('Schema: with number field name', (test) => {
  const schema = Schema.from({
    Dynamic: {},
    field1: 'string',
    1234: { type: 'number' },
  });
  test.strictEqual(schema.kind, 'Dynamic');
  test.strictSame(schema.check({ 1234: 42, field: 'type' }).valid, true);
});
```

**Expected behavior**
It is possible to specify Schema kind without depending on JS engine internals.
This also causes wierd bugs when you create a schema with Object like above and you receive `kind: '123'` and `Dynamic` as "field".

**Comment by georgolden** [comment]
@lundibundi 49c297ab36231c5bcf968e3bdc7dcb222485cbd6 fixed. I added method `isFirstLetter` to metautil about a month ago and just forgot to use. I even did not forget to have `firstKey` as a separate function prepared for this. It has been a long.

Thanks for an issue.

**Comment by georgolden** [comment]
Solved in v2.x
