### ISSUE TITLE
Incorrect data type in test case

### ISSUE THREAD

**Issue by sokoloveugene** [metarhia/metaschema#418]
**Describe the bug**
In the test file `metarhia/metaschema/test/collections.js` schema definition has "Map" data type, but data that should be validated is "Set"

**To Reproduce**
https://github.com/metarhia/metaschema/blob/master/test/collections.js#L73-L83

https://github.com/metarhia/metaschema/blob/master/test/collections.js#L177-L183

**Expected behavior**
```
const obj8 = new Map([
    ['a', 1],
    ['b', 'B'],
  ]);
```

**Comment by sokoloveugene** [comment]
Same for https://github.com/metarhia/metaschema/blob/master/test/collections.js#L177-L183

**Comment by georgolden** [comment]
https://github.com/metarhia/metaschema/blob/master/test/collections.js#L61-L83
https://github.com/metarhia/metaschema/blob/master/test/collections.js#L169-L183

Please check that, there are positive and then negative check in both cases. There are no bugs or errors. Please read this lines carefully.

**Comment by georgolden** [comment]
@sokoloveugene please check and suggest something, or close an issue

**Comment by sokoloveugene** [comment]
Positive check is valid, key and value pairs in Map hast `string` type

```
 const def7 = { type: 'map', key: 'string', value: 'string' };
  const obj7 = new Map([
    ['a', 'A'],
    ['b', 'B'],
  ]);
```

The negative case should check that value types are not `string` in both cases, But now it fails because the data structure is `Set`.

```
  const def8 = { type: 'map', key: 'string', value: 'string' };
  const obj8 = new **Set**([
    ['a', 1],
    ['b', 'B'],
  ]);
  const schema8 = Schema.from(def8);
  test.strictSame(schema8.check(obj8).valid, false);
```

Suggestion: 
```
const def8 = { type: 'map', key: 'string', value: 'string' };
  const obj8 = new **Map**([
    ['a', 1],
    ['b', 'B'],
  ]);
  const schema8 = Schema.from(def8);
  test.strictSame(schema8.check(obj8).valid, false);
```
In this situation test case will demonstrate correct an opposite scenario

**Comment by sokoloveugene** [comment]
@georgolden Sure, please take a look 
https://github.com/metarhia/metaschema/pull/420
