### ISSUE TITLE
Create browser build for metaschema

### ISSUE THREAD

**Issue by georgolden** [metarhia/metaschema#427]
**To-do**

Only place, where we have `metavm` - `lib/loader.js`

- exclude `lib/loader.js` from build files
- `npm run build` for build creation
- Add to package.json import for browsers

**Comment by URVL** [comment]
@tshemsedinov   metaschema do not work in the browser because of the metautil dependency, which in turn is tied to nodejs features.

**Comment by URVL** [comment]
> @tshemsedinov metaschema do not work in the browser because of the metautil dependency, which in turn is tied to nodejs features.

would likely solve the issue of a separate build file from metautil for the browser

**Comment by tshemsedinov** [comment]
@URVL https://github.com/metarhia/metautil/pull/200

**Comment by tshemsedinov** [comment]
Published in metautil 4.0.0

**Comment by tshemsedinov** [comment]
@georgolden @URVL Done in https://github.com/metarhia/metaschema/pull/462
