### ISSUE TITLE
Generate API stub from definition

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metaschema#5]

**Comment by SemenchenkoVitaliy** [comment]
Documentation generator was removed in https://github.com/metarhia/metaschema/pull/182 from [@metarhia/metaschema](https://github.com/metarhia/metaschema) and moved to [@metarhia/metadoc](https://github.com/metarhia/metadoc). As for the issue, API documentation was generated in https://github.com/metarhia/metaschema/pull/231.
