### ISSUE TITLE
Validate Enum decorator

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metaschema#61]
- [ ] `Enum` should be treated as `required: true`
- [ ] Validate fields value to be `Enum.values.includes(value)`
- [ ] `taxonomy/Domains.schema` should be validated including `Enum`

**Comment by lundibundi** [comment]
@tshemsedinov I think second should be
`Enum.has(value)`
?

**Comment by tshemsedinov** [comment]
@lundibundi this is a wrapper needed just for boxing array of values in schemas, no `has, key, from` methods

**Comment by tshemsedinov** [comment]
It will wrap values `{ fieldName: Enum('uno', 'due', 'tre') }` in schemas and when we walidate schema we will find field definition like `Enum { values: ['uno', 'due', 'tre'] }` and use `definition.class.name` to detect that field id `Enum` then check value `definition.values.includes(value)` that's all. No need to implement any utilities because it is metaprogramming and code will be very abstract. @lundibundi

**Comment by tshemsedinov** [comment]
Not relevant for 1.x
