### ISSUE TITLE
discuss: Rename Bitmask -> Flags

### ISSUE THREAD

**Issue by lundibundi** [metarhia/metaschema#90]
This way it's not limiting an internal representation to actually using bitmasks to represent the data.
Also, if anyone has other suggestions for another name feel free to speak out, as I don't think `Flags` is good enough.
Other names may be
* `BitFlags` - I think just `Flags` is better and Bit prefix doesn't bring any value into it
* `Set` - good, but too broad, it may not be intuitive that you can actually use it as Flags.

/cc @tshemsedinov @nechaido @belochub

**Comment by tshemsedinov** [comment]
I agree, `Flags` will be better to express this type usage: `Flags('Uno', 'Due', 'Tre')`
