### ISSUE TITLE
Schema support for non floating numbers

### ISSUE THREAD

**Issue by nechaido** [metarhia/metaschema#98]
Currently, we don't provide a way to define whether a number is an integer or not, also I would be also nice to define desired precision for the number.

I propose to add 2 Domain attributes: `precision` and `floating`.

**Comment by tshemsedinov** [comment]
One attribute is enough, for example: `DomainName: { type: 'number', precision: 'real/double' }` Using pgslq `NUMERIC(precision, scale)` isn't good practice for numbers except `Money` type.

**Comment by lundibundi** [comment]
I'd suggest at least having some enum of types:
`Enum('i32', 'i64', 'u32', 'u64', 'f32', 'f64')` or something,

**Comment by tshemsedinov** [comment]
Why `i8` and `i16` are not included?

**Comment by lundibundi** [comment]
I thought that they are not really useful in a general use case (and I'm not sure if it's possible to properly map them in DB schema generation), but we can as well have them.

**Comment by tshemsedinov** [comment]
Pgsql have `smallint` (i16), `integer` (i32) and `bigint` (i64). It have no `tinyint` type (i8) that may be implemented by `char(1)` or `create domain tinyint as smallint constraint tiny check (value >= 0 and value <= 255);`

**Comment by nechaido** [comment]
@nechaido we should include arbitrary precision numbers to store numbers without precision loss, also having `precision` and `scale` rules for any number is useful for validating user input (values that should have less than a specific amount of fractional digits).
